#---------------------------------#
#      environment configuration  #
#---------------------------------#

version: 0.17.{build}
environment:
  gallery_api_key:
    secure: WeDp1yZJECZBjjW+22A8lA8+gmz+wiYostPKtU4pdLXORfK//eJCdR7f0k3oJ+2r

install:
    - ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
    - ps: Install-WindowsFeature -Name RSAT-Hyper-V-Tools -IncludeAllSubFeature -ErrorAction Stop -Verbose
    - ps: Install-Module -Name Pester, PSSCriptAnalyzer, PSake -Scope CurrentUser -Force -Verbose

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-PSake -BuildFile .\Build.PSake.ps1 -TaskList Appveyor
